### ISSUE TITLE
[Bug]: Recommended pre-commit config can silently ignore files

### ISSUE THREAD

**Issue by srabraham** [aspect-build/bazel-super-formatter#31]
### What happened?

I set up the super-formatter in our .pre-commit-config.yaml [1] in VideoAmp/central, a repo with a lot of files (>3500). I observe that when I run `pre-commit run --all-files bazel-super-formatter`, which is supposed to run the pre-commit on all files in the repo, many files are missed. By contrast, everything works as expected when I run `bazel run @aspect_rules_format//format` (for example, `docs/go/README.md` currently needs formatting at HEAD).
My theory is that pre-commit's batching mechanism isn't working properly with the super formatter.

[1] used this config block (same as from this repo's README):
```yaml
- id: bazel-super-formatter
  name: run bazel super formatter
  language: system
  entry: bazel run @aspect_rules_format//format
  files: .*
  stages: [commit]
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 6.0.0 (bazelisk)

Language(s) and/or frameworks involved:
markdown, shell, js

### How to reproduce

```shell
The "what happened" description lays it out pretty well. For Alex: there are currently 6 files in the repo (which you can access) that need formatting at HEAD, and I'll leave those there for you to see.
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)
